name: Dependabot Auto Merge
uses: ahmadnassri/action-dependabot-auto-merge@v2.3.1

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.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 }}
   
